- name: Install Base Packages (Can take some time)
  ansible.builtin.apt:
    name:
      - git
      - htop
      - vim
      - gh
      - gcc
      - zsh
      - stow
      - fzf
      - tmux
      - build-essential
      - make
      - patch
      - curl
      - wget
      - neovim
      - python3
      - python3-pip
      - python3-poetry
      - tar
      - software-properties-common
      - apt-transport-https
      - lsb-release
      - ca-certificates
      - gnupg
      - libssl-dev
      - libffi-dev
    state: latest
    update_cache: yes

- name: Change shell to zsh
  ansible.builtin.user:
    name: "{{ regular_user }}"
    shell: /usr/bin/zsh
