- name: Add Hashicorp GPG keys
  ansible.builtin.get_url:
    url: https://apt.releases.hashicorp.com/gpg
    dest: /usr/share/keyrings/hashicorp-archive-keyring.gpg
    mode: "0044"

- name: Add Hashicorp Repository
  ansible.builtin.apt_repository:
    repo: "deb [trusted=yes arch=amd64 signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
    filename: /etc/apt/sources.list.d/hashicorp.list
    state: present
    update_cache: true

- name: Install Terraform
  ansible.builtin.apt:
    name: terraform
    state: latest
