- name: Install Kubectl
  ansible.builtin.get_url:
    url: https://dl.k8s.io/release/v1.32.0/bin/linux/arm64/kubectl
    dest: /usr/local/bin/kubectl
    mode: "0755"
- name: Install Kind
  ansible.builtin.get_url:
    url: https://kind.sigs.k8s.io/dl/v0.26.0/kind-linux-amd64
    dest: /usr/local/bin/kind
    mode: "0755"
