- name: Create SSH Dir
  become_user: "{{ regular_user }}"
  ansible.builtin.shell:
    cmd: |
      mkdir {{ home_dir }}/.ssh -p
      chmod 700 {{ home_dir }}/.ssh

- name: Create SSH KeyPair
  become_user: "{{ regular_user }}"
  community.crypto.openssh_keypair:
    path: "{{ home_dir }}/.ssh/id_rsa"

- name: Sudo without password
  ansible.builtin.shell:
    cmd: |
      cp /etc/sudoers /etc/sudoers.bak
      echo "{{ regular_user }} ALL=NOPASSWD:ALL" >> /etc/sudoers
